### ISSUE TITLE
[bug][1.16.1] Configuration file not generating

### ISSUE THREAD

**Issue by Syndaryl** [mactso/Regrowth#1]
I first posted this on CurseForge, but I've realized this is what issue trackers are for...

I'm using Regrowth 1.16.1 v 1.0.0 (SSP) and I'm running into some trouble -

I spawned in a good sized village, with lots of villagers and animals. My game stops responding after a minute or two of entering the world. It ticks along just fine when I uninstall Regrowth.

I'm mostly after the Villager behaviors, so I thought to try turning off the non-villager features, but there's no config file that I can see. I was expecting something like .minecraft\config\regrwoth-common.toml - is it somewhere/something else?

**Comment by mactso** [comment]
Hi!  Thanks for following up in the comments section.
We resolved the issue there.  It was resolved by using a later version of Forge (32.0.47)
I'm still using that village for my test world!
