### ISSUE TITLE
Wall creating with biomes

### ISSUE THREAD

**Issue by zachsai** [mactso/Regrowth#10]
Forge Version : 36.0.0
Minecraft Version: 1.16.5
WorldSeed: 5383803094430116870

**Describe the bug**

![image](https://user-images.githubusercontent.com/63996164/104855887-5d398700-58dd-11eb-9fad-cf4b1b16224b.png)
![image](https://user-images.githubusercontent.com/63996164/104855900-6aef0c80-58dd-11eb-8c70-a97c46c4bc54.png)
making it so frozen rivers use the same wall as snowy tundra please

**Expected behavior**

**Screenshots**

** Stack Trace** 
(Pastebin Link)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mactso** [comment]
Thank you, I've assigned myself this issue.   

ETA roughly 4-10 days if no emergencies come up.

Cheers!

**Comment by mactso** [comment]
I think I fixed this back then.   Please reopen this issue and ping me if not.   I'll be working on Regrowth for the next week or so.
