### ISSUE TITLE
(suggestion) blacksmiths should start building golems when a village gets populated enough

### ISSUE THREAD

**Issue by ekiplier** [mactso/Regrowth#11]
I just thought it would be a really cool feature.
Also, the potion brewer/farmer should place the pumpkin head.
idk much about modding, so I'm not sure if that would be possible to achieve with this mod

And although this is a bit more intrusive, I think that if these features were to be added, golems natural spawning should be removed.

**Comment by mactso** [comment]
Hi there!  
Sorry I missed this back in April.  Probably recovering from the big freeze.

Thank you for contributing a suggestion but this is a bit out of scope for Regrowth.  What I do is look where a mob is and then do something special based on the location and block.  It's very light code.

With Best Regards,
Two Guys,
MacTso
