### ISSUE TITLE
Crash with Biomes you'll go

### ISSUE THREAD

**Issue by WarriorsCode1** [mactso/Regrowth#13]
my game crashes when a pig is "eating" and grass "grows" from an byg overgrown stone grass block. I don't know if this happens with other animals too.

**Comment by mactso** [comment]
Going to retest this this weekend.  I think it is fixed in the lastest version but I didn't test for this error in the last release.
It would grow when a player used bonemeal but only flowers.   It was actually crashing if a player does it too but the crash exception is caught for players.

**Comment by mactso** [comment]
Okay I've confirmed this issue is fixed in the last release.  Thanks for your bug report!

**Comment by mactso** [comment]
This was fixed but had not closed it.  So I reconfirmed it is still fixed.

Confirming this is fixed.   Ran a 24 hour test with pigs on a mixture of grass and overgrown blocks from BYG.   Grassblocks grew, overgrown blocks got some flowers.   No crashes.

Thanks for your issue report.
