### ISSUE TITLE
[Suggestion] Customizable saplings in config

### ISSUE THREAD

**Issue by Neffrex** [mactso/Regrowth#15]
I'm currently playing with this mod alongside Dynamic Trees and I would like to change the regular sapling placement for the Dynamic Trees saplings :D

**Comment by mactso** [comment]
I think there is a setting in Dynamic Trees that makes ordinary saplings convert to dynamic saplings when planted.
Have you tried that?

**Comment by mactso** [comment]
I have enhanced Regrowth to handle dynamic trees as of version 27 in minecraft 1.16.5.   It's also coded for minecraft 1.18.1 but it may not work when the dynamic trees team converts to 1.18.1.   If so I'll fix it- the foundation is in there.

Great Suggestion!
Cheers.
Two Guys,
MacTso

**Comment by djsimmonds** [comment]
hi, i have been using regrowth and dynamic trees for 1.18.2. i just came across this thread where you fixed this in an older version, and said you could fix it when DT updates. any chance you can implement? i tried to find your fix within the code to do a PR but couldn't. thanks.

**Comment by mactso** [comment]
I'm hoping to address this but it's likely to go in 1.19.4 or 1.20 first.
