### ISSUE TITLE
Villager wall check crash? Forge server

### ISSUE THREAD

**Issue by rsslcs** [mactso/Regrowth#19]
Forge Version : -39.0.59
Minecraft Version: 1.18.1
WorldSeed: 

**Describe the bug**
Crash upon approaching a village. (normal Minecraft, not a Stoneholm village)

**To Reproduce**
Crash was random, and unexpected. Upon restart, did not get crash again.

**Expected behavior**
No crash

**Screenshots**
N/A

** Stack Trace** 
https://pastebin.com/V2evWYRg

**Desktop (please complete the following information):**
 - OS: Win10 x64

**Comment by mactso** [comment]
It was trying to print the wall and wall foundation information for an unconfigured biome.
I've fixed this.

If you set the debug level to one, it will print the unknown biome.  Until then, it will default to "plains" for unknown biomes.  If you let me know the unknown biome, I can add it in a future default configuration.

The new version has been posted for approval.
