### ISSUE TITLE
Regrowth Mod doesn't want to load. (1.16.1)

### ISSUE THREAD

**Issue by Leirday** [mactso/Regrowth#2]
Forge Version : 1.16.1-forge-32.0.62
Minecraft Version: 1.16.1

**To Reproduce**
1. Launch Minecraft 
2. See error

**Screenshots**
![Minecraft_ 1 16 1 7_16_2020 3_43_46 PM](https://user-images.githubusercontent.com/63563648/87715419-50e04000-c77b-11ea-86dc-a8d69150addd.png)

**Latest Log** 
https://pastebin.com/RhXGwFQk

**Comment by mactso** [comment]
I'm sorry I missed this.  

We are using it successfully with 32.0.74 and 32.0.93.
I never tested with 32.0.62 specifically.

There are two versions of regrowth right now- one before 32.0.67 and one for after that.

Is the issue still happening to you?

**Comment by mactso** [comment]
Hi.  I'm sorry I missed this.  

Is the issue still occurring?

Thank you!
MacTso.

**Comment by mactso** [comment]
Okay so 
use Regrowth Version 1.16.1 v1.0.0.1 for Forge versions 32.0.24 to 32.0.66 
use Regrowth Version 1.16.1 v1.0.0.5 for Forge versions 32.0.67 and higher.
It may fail again in 32.0.98 right now.  I'll have a version (v1.98.0.6) which should work for 32.0.67 to 32.0.98 (and higher) by wednesday.
Cheers!
