### ISSUE TITLE
fabric addition .30 on curseforge has the forge version in download link.

### ISSUE THREAD

**Issue by JonCaver** [mactso/Regrowth#21]
Pretty much like the tittle says.
Downloaded the file and noticed it didn't have fabric in the file name like the .28 version but thought maybe it was just changed.
Loaded up the game after deleting the config to repopulate it with a new one and noticed it didn't create a new one.
So it must have been the forge version by mistake.
Hope this helps!

**Comment by JonCaver** [comment]
looked again and its working now. was probably a curseforge error while they were having problems with loading. Cheers

**Comment by mactso** [comment]
Okay glad to hear it was resolved.  I hadn't seen the message yet.
My message priorities are
Discord (often hourly)
Curseforge forum (daily)
Reported issues (once a week)

Glad the issue cleared up!






On Saturday, May 7, 2022, 12:21:05 AM CDT, JonCaver ***@***.***> wrote: 







looked again and its working now. was probably a curseforge error while they were having problems with loading. Cheers

**Comment by mactso** [comment]
Okay, glad this cleared up. Hadn't seen your issue yet.

Okay glad to hear it was resolved.  I hadn't seen the message yet.

My message priorities are
Discord (often hourly)
Curseforge forum (daily)
Reported issues (once a week)

Glad the issue cleared up!
