### ISSUE TITLE
Crash regrowth

### ISSUE THREAD

**Issue by Jollyolsport** [mactso/Regrowth#22]
Forge Version : 40.1.0
Minecraft Version:  1.18.2

random crash

**Expected behavior**

**Screenshots**

** Stack Trace** 
(Pastebin Link)

[crash-2022-05-05_13.19.09-server.txt](https://github.com/mactso/Regrowth/files/8633320/crash-2022-05-05_13.19.09-server.txt)

**Comment by mactso** [comment]
Disable the "tall" action for creepers.  It's trying to grow grass on a the stone grass BYG block.   

BYG  fixed this issue on the forge side a few months ago.  It is set as fertilizable/growable but fails if you try to fertilize it.   I'll try to add a check for that block by wednesday the 10th.

It will also be a problem if players use bonemeal on that block most likely.

**Comment by mactso** [comment]
Okay, this is fixed in version 30b.
