### ISSUE TITLE
Debug Level 0 still too spammy

### ISSUE THREAD

**Issue by dragonmaus** [mactso/Regrowth#23]
Fabric Version : 0.53.4+1.18.2
Minecraft Version: 1.18.2
WorldSeed: -4349325659081433721

**Describe the bug**
With the debugLevel option set to `0`, Regrowth still fills the log with an endless stream of messages. One random selection of ten seconds worth of logging contained about 60 lines of just Regrowth warning about "minecraft:forest wall improvement".

**To Reproduce**
1. Launch a Minecraft server.
2. Log in with a client.
3. Watch the log fill up.

**Expected behavior**
`debugLevel=0` should log initialisation messages, errors, and little, if anything, else. Information about improvements and villager actions should be reserved for higher debug levels.

**Log**
https://pastebin.com/UedJ6FaT

**Additional context**
I do have some things installed on the server that may increase the number and/or size of villages (ChoiceTheorem's Village Overhaul datapack is the most likely candidate), which would exacerbate the severity of this issue.

**Comment by mactso** [comment]
There should be only one or two messages total from regrowth on startup at level 0.   I must have left in a development message.   Sorry about that.   I'll put out a fix asap.  Probably by tomorrow morning.

**Comment by mactso** [comment]
I've located the debugging statement.  I had temporarily lowered it to 0 to verify the functionality was being executed after the conversion and missed it.  I did a check for any other debugging statements at 0 in the main event loop and found one for villagers on a wall perimeter.  I set it to level 1 as well.

Building version 30d for fabric now.  Will upload after testing.

**Comment by mactso** [comment]
Okay, I also verified this was not an issue with 1.16.5 for fabric.  I guess I fixed those messages when I made the 1.16.5 from the 1.18.2 version.

You should be good to go!  I'll close this when I hear from you or next wednesday.

**Comment by dragonmaus** [comment]
Awesome! Thanks for digging into it.

**Comment by mactso** [comment]
You are welcome.  I appreciated feedback on my mods.  Problems, suggestions, etc.

Cheers!
Two Guys
MacTso
