### ISSUE TITLE
无法启动服务器

### ISSUE THREAD

**Issue by WYL23456** [mactso/Regrowth#24]
[latest.log](https://github.com/mactso/Regrowth/files/8929074/latest.log)
1.16.5 fabric

**Comment by mactso** [comment]
This is a warning because they do not like my version number for the bugfix release ("30c").   It should run fine for now but going forward I'll need to change to a 3 tuple system.
(30.0.1, 30.0.2, etc.)

**Comment by WYL23456** [comment]
OK，Thank you for your

**Comment by mactso** [comment]
There should be an update for Fabric soon.   I'm just waiting for 1.19.1 to be released.
