### ISSUE TITLE
Incompatibility with Natural Progression

### ISSUE THREAD

**Issue by emanuele246gi** [mactso/Regrowth#27]
Forge Version: 40.1.69
Minecraft Version: 1.18.2

**Describe the bug**
Villagers do not build walls on blocks with pebbles and sticks, despite being like grass: that disappear when a block gets placed on them.

**To Reproduce**
1. Find a village
2. Wait until they start build walls
3. Notice when they skip a spot occupied by a pebble or a stick (if not, you should be able to reproduce this even by manually placing them.

**Expected behavior**
To substitute them just like tall grass or flowers

**Screenshots**
![2022-08-06_15 14 45](https://user-images.githubusercontent.com/61762317/183250515-f96018c5-c721-4a67-b021-3547979d19ef.png)

**Comment by mactso** [comment]
Thanks for your report.   That's going to be tough to fix since I can't compile against their files.

I'll look into it this week.  

Can you look at them with F3 and give me the "modname:blockname"?

**Comment by emanuele246gi** [comment]
Sure!
natprog:stone_pebble
natprog:andesite_pebble
natprog:diorite_pebble
natprog:granite_pebble
natprog:sandstone_pebble
natprog:red_sandstone_pebble
natprog:tuff_pebble
natprog:deepslate_pebble
natprog:dripstone_block_pebble
natprog:netherrack_pebble
natprog:end_stone_pebble

Here there are stone types from other mods:
natprog:quark_limestone_pebble
natprog:quark_jasper_pebble
natprog:create_asurine_pebble
natprog:create_crimsite_pebble
natprog:create_limestone_pebble
natprog:create_ochrum_pebble
natprog:create_scorchia_pebble
natprog:create_scoria_pebble
natprog:create_veridium_pebble

And here it is the stick:
natprog:twigs

Thank you for your effort and patience, man!

**Comment by mactso** [comment]
Thanks!

Looks like I can look for natprogs:*pebble and natprogs:twig.

**Comment by emanuele246gi** [comment]
Thank you!

**Comment by mactso** [comment]
Sure.  I'll still need to do some new program to see them on the ground and remove them so it will be a little bit.  But definately as part of going to 19 and the change will be in 18 too.

**Comment by mactso** [comment]
Have a friend who is getting major surgery in 8 days so that may delay it.

**Comment by emanuele246gi** [comment]
No problem man, I'm not in a hurry for this

**Comment by mactso** [comment]
I've started work on this now.

**Comment by mactso** [comment]
![image](https://user-images.githubusercontent.com/9662494/185362452-5c89cd10-972e-44b6-8e7b-cf4ed854f5b4.png)

This issue is fixed in version 31 for 1.18.1 now.   The code changes are in for 1.18.2 (the version you are in) and I'll test them tomorrow (it's 4am. lol).

Then I'll do 1.19.1 for forge and fabric.
May do a 1.18.2 for fabric depending on how hard it looks.

**Comment by emanuele246gi** [comment]
Thank you so much!

**Comment by mactso** [comment]
1.18.2 is submitted for approval.

Please let me know if it works and we can close the issue.

**Comment by emanuele246gi** [comment]
Sorry for the long wait, but yes! It works! Thank you so much man!
