### ISSUE TITLE
[1.15.2] Ticking entity crash on dedicated server

### ISSUE THREAD

**Issue by katubug** [mactso/Regrowth#3]
Forge Version: 31.2.31
Minecraft Version: 1.15.2
WorldSeed: -5828303611848360714

**Describe the bug**
Dedicated multiplayer server crashes occasionally, unsure of details.

**To Reproduce**
1. Unsure, three of us were playing as usual - building or exploring - when this happened

** Stack Trace** 
https://pastebin.com/88BKAhFa

**Comment by mactso** [comment]
Looking into this.

Are you using the default code where the cows both eat and grow grass?
Have you used the forge "remove ticking entities" setting? (by default it's false).

**Comment by mactso** [comment]
Okay the code there is very simple- no loops.  It basically just destroys one block or bonemeal's once. 

Not sure what is going on and can't duplicate the issue yet.

In the meantime- here is a fix to get you going.

Look in saves/serverconfig/forge.toml
Set this value to true.
	removeErroringEntities = false
Start and stop your server.
Reset this value to false.
	removeErroringEntities = false

I'll look at this more tomorrow when I'm fresh.

**Comment by mactso** [comment]
Okay, I didn't find an obvious issue but I did see several places where I assumed something existed.   I have added a bunch of checks for "null" values in those places.

I also added some debugLevel=2 debugging statements for "trying to eat" and "trying to grow".

The new version is Regrowth 1.16.1 1.0.0.5.

I'm now adding these new protective changes to version 1.15.1/1.15.2.

I hope this will prevent the issue from reoccuring in your world.

**Comment by mactso** [comment]
I'll give you another update when the 1.15.2 version is ready for you to download.

**Comment by katubug** [comment]
Thanks a bunch!

**Comment by mactso** [comment]
Okay the 1.15.2 version 1.0.0.5 has been approved.
It has extra protection against null pointers ( which I saw in the crash log).
It has a couple advancements.

There will be a 1.0.0.6 version soon which will have the villager logic improvements so they build walls better when they are hanging off the edge of blocks.
And a 1.0.0.6 version 1.16.1 version which will have the advancements (bringing both 1.15.1/2 and 1.16.1 into sync).

**Comment by mactso** [comment]
Final update....
1.15.1/2 and 1.16.1 are now feature synchronized and have the new null pointer protection.   Reopen and let me know if you see the failure again!
