### ISSUE TITLE
[1.16.2] java.lang.NullPointerException: Ticking entity

### ISSUE THREAD

**Issue by VoiidInVaiin** [mactso/Regrowth#4]
Crash: https://pastebin.com/DSQ9vPCX

+ I have remove erroring entities on and the crash still happens

**Comment by mactso** [comment]
This has been identifed and a fix is being built for this now.    Should be submitted for approval in the next few minutes.

But just in case, please provide worldseed and x,y,z location.

**Comment by mactso** [comment]
This should be fixed now!
Thanks for creating the issue.
