### ISSUE TITLE
Regrowth and Survive hitting mob causes Crash

### ISSUE THREAD

**Issue by Figgmastah** [mactso/Regrowth#46]
Forge Version : 40.2.0
Minecraft Version: 1.18.2
WorldSeed: Any

**Describe the bug**
When hitting a mob with Regrowth and Survive installed game crashes.

**To Reproduce**
1. Create new world
2. Find a mob
3. Punch it

**Expected behavior**
When hitting a mob the game won't crash.

![Skjermbilde (281)](https://github.com/mactso/Regrowth/assets/76262849/aeb1faa5-ecec-4a7c-b2b0-c414f58bd774)

**Comment by mactso** [comment]
Could you "view crash report" and add that to the ticket?  That way we can see which mod is throwing the illegal argument exception.

I'm unfamiliar with Survive.  I'll have to take a look at it.

Thanks!

**Comment by Figgmastah** [comment]
[crash-2023-05-24_23.33.02-client.txt](https://github.com/mactso/Regrowth/files/11559358/crash-2023-05-24_23.33.02-client.txt)

**Comment by mactso** [comment]
Okay, I've looked into this and it doesn't appear to be related to regrowth.  At least not directly in any way I can see.
Regrowth doesn't use attributes and isn't in the crash log.

All regrowth does it intercept the mob movement event, and check the block they are standing on and then possibly change the state of that block to a new block.

Going to close this issue for now.   Sorry for the delay, I had no power 7 days in May from a Derecho wind storm and then no power 7 days in July from a Hurricane.    Really beat me up there for a while.

Cheers,
Two Guys,
MacTso
