### ISSUE TITLE
[Suggestion] Upload to Modrinth

### ISSUE THREAD

**Issue by nco2k** [mactso/Regrowth#49]
it would be cool if you could upload your mod to modrinth as well.

**Comment by mactso** [comment]
I was leery of Modrinth because of Curseforge requirements that they be the sole source but it's becoming clear that many mod authors are going to Modrinth as well as Curseforge so I'm going to look into it.   Is there any helpful suggestion on how to get the process started?

I've been struggling with SADS in the winter plus some health issues since last August but I'm recovering finally and winter is ending so the seasonal affective disorder should start reducing.

**Comment by darceno** [comment]
I've been using the Modrinth launcher to play modded for a while now, and I would **love** to see Regrowth there as well. Basically, all the main mods I use are there - even masa uploaded Litematica and MiniHUD there last week. I don't think Curseforge would make it a problem for you, right?

**Comment by mactso** [comment]
I have uploaded FixExperienceBug to Modrinth.

Please let me know if it looks like I did it correctly.  I'll slowly start uploading other mods over there if that one looks good.

**Comment by darceno** [comment]
Just checked, basically all looking good! You just didn't add 1.20/1.20.1 support for the _fabric-experiencebugfix-1.20_ version. This way it won't show up when trying to install it for a 1.20.1 instance throught the Modrinth launcher search. But that's very easy to fix.

Nothing wrong I could see besides that. Excited to see Regrowth there!

**Comment by mactso** [comment]
I have uploaded the latest 1.20 versions of Regrowth for forge and fabric.   And I've uploaded the 1.21.1 conversion of Regrowth for Forge.  The Regrowth for 1.21.1 Fabric is likely to be a few weeks.  I need to work on several Forge conversions to lock those skillsets in and to learn all the conversion bugs/changes.

Energy levels continue to improve as is my sleep.  Hope we do not get another natural disaster!

It looks like the fabric 1.20 and 1.20.1 is the same mod as 1.20.2-1.20.5.   I'll have to edit that and fix it.  Thanks for the feedback, I appreciate it!

**Comment by calliecameron** [comment]
Could you add the fabric 1.19.2 version too? Only the forge 1.20 version is showing up at https://modrinth.com/mod/regrowth/versions.

**Comment by mactso** [comment]
Sorry, new to Modrinth.  I'll add it if it exists.

**Comment by calliecameron** [comment]
That's still not quite what I'm looking for - that's the fabric 1.19.4 version (fabric-release-regrowth-1.19.4-31.1.0.jar) - what I'm looking for is the fabric 1.19.2 version (fabric-release-regrowth-1.19-31.1.0.jar).
