### ISSUE TITLE
Desert villagers place smooth sandstone inside houses

### ISSUE THREAD

**Issue by LlubNek** [mactso/Regrowth#5]
Regrowth-1.16.2-1.16.3-1.21.0.14.jar
Forge Version: 34.1.35
Minecraft Version:  1.16.3
WorldSeed: -468233840

**Describe the bug**
Desert villagers place smooth sandstone below them whenever there is no solid block beneath them.  If they walk up onto a block inside their house, they will soon fill the house to that level with smooth sandstone as they wander around.   They also break beds and doors (by replacing them with smooth sandstone).

**To Reproduce**
1. find a desert village
2. find a house with a villager inside
3. observe the rising tide of smooth sandstone
4. break block under villager to seem him make a new one instantly

**Expected behavior**
Maybe only place sandstone when there's no blocks above the villager and don't replace anything that isn't "replaceable" (like tall grass, flowers, or dead bushes)

**Screenshots**
![2020-11-01_19 06 26](https://user-images.githubusercontent.com/313762/97819265-6c614f00-1c75-11eb-8657-ad9e21acc2d2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 (why are you asking for browser and mobile device info...?)

**Additional context**
This is probably the "road upgrades" feature gone wild.

**Comment by mactso** [comment]
Thanks, I'll give that a look asap!
They are not supposed to do that if there is a bed or workstation within 7 meters.

**Comment by mactso** [comment]
As a temporary fix- disable road improvements.  That's going to be where the issue is.

**Comment by mactso** [comment]
Okay, the villager thought that it  was fixing potholes in the road.   
The villager will now check to see if it can see the sky before fixing potholes in desert settings.  I wish they didn't use the same blocks for buildings and roads.  It's been tricky.

I'll be posting this as version 15 soon.
