### ISSUE TITLE
Crash together with citadel

### ISSUE THREAD

**Issue by smallerYeet** [mactso/Regrowth#6]
Forge Version : 34.1.42
Minecraft Version: 1.16.3
WorldSeed: //

The Bug is crashing my game when used together with [citadel](https://www.curseforge.com/minecraft/mc-mods/citadel/files)
Dont know what else i should say about this

This happens every time i load/create a World.
This is the log, its too large for pastebin
https://cdn.discordapp.com/attachments/738561074504138834/775746214128779284/latest.log

 - OS: Windows 10

**Comment by mactso** [comment]
Thank you for the bug report. I'm reviewing it now.

**Comment by mactso** [comment]
Could you give me a list of your mods?

with only citadel and regrowth, it is crashing with a missing oredictionary.

However- the log you provided gave me enough info for a fix.  Basically something that always exists (the list of overworld blocks that count as stone) doesn't exist (yet?) in this case.  

This was the code where the skeletons planted mushrooms.  I added a little code to check if the list was null before asking it if the block the skeletons were standing for was in the list.

I'm going to go ahead and post this fix.
