### ISSUE TITLE
No villager flags in the config file

### ISSUE THREAD

**Issue by LlubNek** [mactso/Regrowth#8]
Regrowth-1.16.4-1.16.4-1.35.0.18.jar
Forge Version:  35.1.28
Minecraft Version:  1.16.4

**Describe the bug**
The config file contains no flags to control villager behaviour.  Road upgrades are still problematic, so this is definitely needed.

**To Reproduce**
1. start with a fresh minecraft instance
2. install the mod
3. run minecraft to generate config
4. open config file
5. note absence of villager flags

**Expected behavior**
A villager flags line as described in the mod description on curseforge should appear in the `["Regrowth Control Values"]` section of the config file (or a batch of booleans to control the same behaviour).

**Comment by mactso** [comment]
I'll give it a look.
I need
1) the forgeversion
2) the minecraft version
3) the worldseed.

I just tested the 1.16.4 version in 1.16.4 and 1.16.3 and get the line.

["Regrowth Mobs 6464"]
	#RegrowthMobs String 6464
	defaultRegrowthMobsActual = "minecraft:cow,both,240.0;minecraft:horse,eat,360.0;minecraft:donkey,eat,360.0;minecraft:sheep,eat,240.0;minecraft:pig,grow,800.0;minecraft:bee,grow,1000.0;minecraft:chicken,grow,600.0;minecraft:villager,crwplvt,5.0;minecraft:creeper,tall,60.0;minecraft:zombie,stumble,180.0;minecraft:skeleton,mushroom,180.0"


Note the "minecraft:villager,crwplvt,5.0;" entry just after chickens and just before creepers.

**Comment by LlubNek** [comment]
Sorry, not sure how I missed that... I searched maybe five times, but I see it there now...
You might want to consider doing the villager flags separately though.

**Comment by mactso** [comment]
I think I could move them to the start of the default list next release.  They were originally at the end of the default file and got buried as I added more options.

I'm glad you found them.  Cheers!
