### ISSUE TITLE
[Suggestion] Torch Options dissociated from other options

### ISSUE THREAD

**Issue by Toilet-Lord** [mactso/Regrowth#9]
_I am putting this suggestion here so you can close it if you don't like it and it wont end up in the comments cluttering with all the others._

**I installed the mod and I absolutely love it.** 

Except that I find that the villagers place way too many torches and there's some options for torches in the config files but those options ALSO affect other things like villagers putting walls (which I like)

I think separating torches from other options would be great and not too time-consuming (as far as I know, I'm not a good coder like you) since the codes are already there?

The options could be as follows:
```
#on=1 off=0
Torches on walls=1;
Torches in and on buildings=1;
Torches around village=0;
```
or following your logic:
```
Q= Villagers place torches on walls
E= Villagers place torches in buildings and outside, on the walls
A= Villagers place torches around the village, mostly on the surface block
```
**Or adding an option to modify the radius around placed torches so there's no clusters like in the image below:**
```
#The radius in which no torch can be placed by villagers around a torch already placed (by a villager) 
Torchradius=15
```

[etc..]

![2021-01-09_17 18 46](https://user-images.githubusercontent.com/76745705/104110217-846fd300-52a3-11eb-94db-e2c595067cff.png)

let me know of your response

**Comment by mactso** [comment]
Right now wall torches don't care about light level and torches on the ground do care. 
So if the villagers place torches on the ground and then build a wall, A village can end up with extra torches around walls.

Currently, ground torches are placed when a villager can't see the sky and when the light level is low enough that a monster would spawn there and they roll 1/60.

I could give control over the light level for ground torches so they place torches further apart or not at all (by setting the light level for ground torches to below 0).  I'm also thinking about lantern posts for dark areas next to paved grass..

Right now my focus is on the hostile water mobs and then the 1.12.2 version of regrowth.  I can add this feature in when I do the 16.5 update.

**Comment by mactso** [comment]
Just a followup.  The work on Hostile Water Mobs and 1.12.2 Regrowth is complete.

I'm planning on letting you configure the light level where villagers will light so you can have them put down suboptimal lighting.

**Comment by mactso** [comment]
Coding this now.  Expect will be in soon.
Going over all the pending suggestions and requests before a 17 version.

**Comment by mactso** [comment]
FYI: This went in back then but I didn't close the issue.  I apologize.  I was just reviewing all open issues and saw this was open.

Here is the config line for your requested enhancement.

"Torch Light Level - Villagers will only place torches on blocks this dark or darker.")
Values: 0-10
Default: 7

If you set it to 10, they will place torches about 4 spaces apart.
if you set it to 7, they will place torches about 8 spaces apart.
If you set it to 0, they'll place torches about 16 spaces apart (so rare)
